In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('ag_news.csv')

In [4]:
df

Class Index                                              Title  \
0                 3  Wall St. Bears Claw Back Into the Black (Reuters)   
1                 3  Carlyle Looks Toward Commercial Aerospace (Reu...   
2                 3    Oil and Economy Cloud Stocks' Outlook (Reuters)   
3                 3  Iraq Halts Oil Exports from Main Southern Pipe...   
4                 3  Oil prices soar to all-time record, posing new...   
...             ...                                                ...   
119995            1  Pakistan's Musharraf Says Won't Quit as Army C...   
119996            2                  Renteria signing a top-shelf deal   
119997            2                    Saban not going to Dolphins yet   
119998            2                                  Today's NFL games   
119999            2                       Nets get Carter from Raptors   

                                              Description  
0       Reuters - Short-sellers, Wall Street's dwindli...  
1       Reuters - Private investment firm Carlyle Grou...  
2       Reuters - Soaring crude prices plus worries\ab...  
3       Reuters - Authorities have halted oil export\f...  
4       AFP - Tearaway world oil prices, toppling reco...  
...                                                   ...  
119995   KARACHI (Reuters) - Pakistani President Perve...  
119996  Red Sox general manager Theo Epstein acknowled...  
119997  The Miami Dolphins will put their courtship of...  
119998  PITTSBURGH at NY GIANTS Time: 1:30 p.m. Line: ...  
119999  INDIANAPOLIS -- All-Star Vince Carter was trad...  

[120000 rows x 3 columns]

In [5]:
df['Title'].isnull().sum()

np.int64(0)

In [6]:
df['Class Index']

0         3
1         3
2         3
3         3
4         3
         ..
119995    1
119996    2
119997    2
119998    2
119999    2
Name: Class Index, Length: 120000, dtype: int64

In [7]:
df=df.rename(columns={'Class Index':'class'})

In [8]:
df

class                                              Title  \
0           3  Wall St. Bears Claw Back Into the Black (Reuters)   
1           3  Carlyle Looks Toward Commercial Aerospace (Reu...   
2           3    Oil and Economy Cloud Stocks' Outlook (Reuters)   
3           3  Iraq Halts Oil Exports from Main Southern Pipe...   
4           3  Oil prices soar to all-time record, posing new...   
...       ...                                                ...   
119995      1  Pakistan's Musharraf Says Won't Quit as Army C...   
119996      2                  Renteria signing a top-shelf deal   
119997      2                    Saban not going to Dolphins yet   
119998      2                                  Today's NFL games   
119999      2                       Nets get Carter from Raptors   

                                              Description  
0       Reuters - Short-sellers, Wall Street's dwindli...  
1       Reuters - Private investment firm Carlyle Grou...  
2       Reuters - Soaring crude prices plus worries\ab...  
3       Reuters - Authorities have halted oil export\f...  
4       AFP - Tearaway world oil prices, toppling reco...  
...                                                   ...  
119995   KARACHI (Reuters) - Pakistani President Perve...  
119996  Red Sox general manager Theo Epstein acknowled...  
119997  The Miami Dolphins will put their courtship of...  
119998  PITTSBURGH at NY GIANTS Time: 1:30 p.m. Line: ...  
119999  INDIANAPOLIS -- All-Star Vince Carter was trad...  

[120000 rows x 3 columns]

In [9]:
neworder=['Title','Description','class']

In [10]:
df=df.reindex(columns=neworder)

In [11]:
df

Title  \
0       Wall St. Bears Claw Back Into the Black (Reuters)   
1       Carlyle Looks Toward Commercial Aerospace (Reu...   
2         Oil and Economy Cloud Stocks' Outlook (Reuters)   
3       Iraq Halts Oil Exports from Main Southern Pipe...   
4       Oil prices soar to all-time record, posing new...   
...                                                   ...   
119995  Pakistan's Musharraf Says Won't Quit as Army C...   
119996                  Renteria signing a top-shelf deal   
119997                    Saban not going to Dolphins yet   
119998                                  Today's NFL games   
119999                       Nets get Carter from Raptors   

                                              Description  class  
0       Reuters - Short-sellers, Wall Street's dwindli...      3  
1       Reuters - Private investment firm Carlyle Grou...      3  
2       Reuters - Soaring crude prices plus worries\ab...      3  
3       Reuters - Authorities have halted oil export\f...      3  
4       AFP - Tearaway world oil prices, toppling reco...      3  
...                                                   ...    ...  
119995   KARACHI (Reuters) - Pakistani President Perve...      1  
119996  Red Sox general manager Theo Epstein acknowled...      2  
119997  The Miami Dolphins will put their courtship of...      2  
119998  PITTSBURGH at NY GIANTS Time: 1:30 p.m. Line: ...      2  
119999  INDIANAPOLIS -- All-Star Vince Carter was trad...      2  

[120000 rows x 3 columns]

In [12]:
import re
from nltk.stem import WordNetLemmatizer

In [13]:
corpus=[]
for i in range(0,len(df)):
    review=re.sub('[^a-zA-Z0-9]',' ',df['Title'][i])
    review=review.lower()
    review=review.split()
    
    review=' '.join(review)
    corpus.append(review)

In [14]:
corpus

['wall st bears claw back into the black reuters',
 'carlyle looks toward commercial aerospace reuters',
 'oil and economy cloud stocks outlook reuters',
 'iraq halts oil exports from main southern pipeline reuters',
 'oil prices soar to all time record posing new menace to us economy afp',
 'stocks end up but near year lows reuters',
 'money funds fell in latest week ap',
 'fed minutes show dissent over inflation usatoday com',
 'safety net forbes com',
 'wall st bears claw back into the black',
 'oil and economy cloud stocks outlook',
 'no need for opec to pump more iran gov',
 'non opec nations should up output purnomo',
 'google ipo auction off to rocky start',
 'dollar falls broadly on record trade gap',
 'rescuing an old saver',
 'kids rule for back to school',
 'in a down market head toward value funds',
 'us trade deficit swells in june',
 'shell could be target for total',
 'google ipo faces playboy slip up',
 'eurozone economy keeps growing',
 'expansion slows in japan',
 'ra

In [15]:
sentence_length=max(len(i.split()) for i in corpus)

In [16]:
sentence_length

24

In [17]:
from tensorflow.keras.layers import TextVectorization

In [18]:
tv=TextVectorization(output_mode='int',output_sequence_length=sentence_length)

In [19]:
tv.adapt(corpus)

In [20]:
tokenized_corpus=tv(corpus)

In [21]:
corpus[4]

'oil prices soar to all time record posing new menace to us economy afp'

In [22]:
tokenized_corpus[4]

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([   23,    60,  1512,     2,   157,   105,    80, 13280,    19,
        8033,     2,    17,   291,    34,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0])>

In [23]:
from tensorflow.keras.layers import Embedding, Dense, LSTM,Input
from tensorflow.keras.models import Sequential

In [24]:
vector_representation_size=100

In [25]:
model=Sequential([
    Input(shape=(sentence_length,))
])

In [26]:
vocab_size=len(tv.get_vocabulary())

In [27]:
print(vocab_size)

33527


In [28]:
model.add(Embedding(input_dim=vocab_size,output_dim=vector_representation_size))

In [29]:
model.add(LSTM(200))

In [30]:
model.add(Dense(4,activation='softmax'))

In [31]:
from tensorflow.keras.optimizers import AdamW

In [32]:
model.compile(loss='sparse_categorical_crossentropy',optimizer=AdamW(learning_rate=1e-3),metrics=['accuracy'])

In [33]:
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 24, 100)        │     3,352,700 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 200)            │       240,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 4)              │           804 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,594,304 (13.71 MB)

 Trainable params: 3,594,304 (13.71 MB)

 Non-trainable params: 0 (0.00 B)

In [34]:
df

Title  \
0       Wall St. Bears Claw Back Into the Black (Reuters)   
1       Carlyle Looks Toward Commercial Aerospace (Reu...   
2         Oil and Economy Cloud Stocks' Outlook (Reuters)   
3       Iraq Halts Oil Exports from Main Southern Pipe...   
4       Oil prices soar to all-time record, posing new...   
...                                                   ...   
119995  Pakistan's Musharraf Says Won't Quit as Army C...   
119996                  Renteria signing a top-shelf deal   
119997                    Saban not going to Dolphins yet   
119998                                  Today's NFL games   
119999                       Nets get Carter from Raptors   

                                              Description  class  
0       Reuters - Short-sellers, Wall Street's dwindli...      3  
1       Reuters - Private investment firm Carlyle Grou...      3  
2       Reuters - Soaring crude prices plus worries\ab...      3  
3       Reuters - Authorities have halted oil export\f...      3  
4       AFP - Tearaway world oil prices, toppling reco...      3  
...                                                   ...    ...  
119995   KARACHI (Reuters) - Pakistani President Perve...      1  
119996  Red Sox general manager Theo Epstein acknowled...      2  
119997  The Miami Dolphins will put their courtship of...      2  
119998  PITTSBURGH at NY GIANTS Time: 1:30 p.m. Line: ...      2  
119999  INDIANAPOLIS -- All-Star Vince Carter was trad...      2  

[120000 rows x 3 columns]

In [35]:
x=df.drop(labels='class',axis=1)

In [36]:
y=df['class']-1 #sparse_cat_cross wants labels from 0 not from 1

In [37]:
y.value_counts()

class
2    30000
3    30000
1    30000
0    30000
Name: count, dtype: int64

In [38]:
import numpy as np

In [39]:
x=np.array(tokenized_corpus)

In [40]:
y=np.array(y)

In [41]:
x

array([[ 490,  316,  917, ...,    0,    0,    0],
       [9498,  530, 1101, ...,    0,    0,    0],
       [  23,   22,  291, ...,    0,    0,    0],
       ...,
       [5367,   51, 1067, ...,    0,    0,    0],
       [ 699,    6,  439, ...,    0,    0,    0],
       [1057,  117, 1572, ...,    0,    0,    0]], shape=(120000, 24))

In [42]:
x.shape,y.shape

((120000, 24), (120000,))

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1,stratify=y)

In [45]:
import tensorflow 

In [46]:
early_stopping=tensorflow.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    verbose=1,
    min_delta=0.001,
    patience=3,
    restore_best_weights=True,
    mode='auto'
)

In [47]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=128,callbacks=[early_stopping])  

Epoch 1/10
657/657 ━━━━━━━━━━━━━━━━━━━━ 82s 123ms/step - accuracy: 0.7445 - loss: 0.6345 - val_accuracy: 0.8599 - val_loss: 0.4239
Epoch 2/10
657/657 ━━━━━━━━━━━━━━━━━━━━ 79s 120ms/step - accuracy: 0.8963 - loss: 0.3139 - val_accuracy: 0.8607 - val_loss: 0.4108
Epoch 3/10
657/657 ━━━━━━━━━━━━━━━━━━━━ 103s 156ms/step - accuracy: 0.9205 - loss: 0.2436 - val_accuracy: 0.8669 - val_loss: 0.4047
Epoch 4/10
657/657 ━━━━━━━━━━━━━━━━━━━━ 92s 139ms/step - accuracy: 0.9331 - loss: 0.2065 - val_accuracy: 0.8663 - val_loss: 0.4227
Epoch 5/10
657/657 ━━━━━━━━━━━━━━━━━━━━ 83s 127ms/step - accuracy: 0.9410 - loss: 0.1792 - val_accuracy: 0.8591 - val_loss: 0.4791
Epoch 6/10
657/657 ━━━━━━━━━━━━━━━━━━━━ 77s 118ms/step - accuracy: 0.9485 - loss: 0.1522 - val_accuracy: 0.8610 - val_loss: 0.5090
Epoch 6: early stopping
Restoring model weights from the end of the best epoch: 3.


In [48]:
y_pred=model.predict(x_test)

1125/1125 ━━━━━━━━━━━━━━━━━━━━ 12s 11ms/step


In [49]:
y_pred_labels=np.argmax(y_pred,axis=1)

In [50]:
y_pred_labels

array([3, 0, 2, ..., 3, 2, 0], shape=(36000,))

In [51]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,log_loss,roc_auc_score

In [52]:
print(classification_report(y_test,y_pred_labels))

              precision    recall  f1-score   support

           0       0.89      0.86      0.87      9000
           1       0.91      0.91      0.91      9000
           2       0.84      0.85      0.84      9000
           3       0.84      0.86      0.85      9000

    accuracy                           0.87     36000
   macro avg       0.87      0.87      0.87     36000
weighted avg       0.87      0.87      0.87     36000



In [53]:
print(confusion_matrix(y_test,y_pred_labels))

[[7724  386  502  388]
 [ 319 8169  268  244]
 [ 328  207 7611  854]
 [ 350  214  730 7706]]


In [54]:
print(accuracy_score(y_test,y_pred_labels))

0.8669444444444444


In [55]:
print(log_loss(y_test,y_pred))

0.4047011972482275


In [56]:
print(roc_auc_score(y_test,y_pred,multi_class='ovr'))

0.9702741260288066


Now trying Bidirectional LSTM

In [57]:
from tensorflow.keras.layers import Bidirectional,Dropout

In [58]:
model1=Sequential([
    Input(shape=(sentence_length,))
    ])

In [59]:
model1.add(Embedding(input_dim=vocab_size,output_dim=vector_representation_size))

In [60]:
model1.add(Dropout(0.2))

In [61]:
model1.add(Bidirectional(LSTM(200)))

In [62]:
model1.add(Dropout(0.2))

In [63]:
model1.add(Dense(4,activation='softmax'))

In [64]:
model1.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [65]:
model1.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 24, 100)        │     3,352,700 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 24, 100)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 400)            │       481,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 400)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │         1,604 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,835,904 (14.63 MB)

 Trainable params: 3,835,904 (14.63 MB)

 Non-trainable params: 0 (0.00 B)

In [66]:
model1.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64,callbacks=[early_stopping])

Epoch 1/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 166s 125ms/step - accuracy: 0.8074 - loss: 0.5226 - val_accuracy: 0.8669 - val_loss: 0.3862
Epoch 2/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 203s 154ms/step - accuracy: 0.9022 - loss: 0.2816 - val_accuracy: 0.8722 - val_loss: 0.3676
Epoch 3/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 181s 138ms/step - accuracy: 0.9242 - loss: 0.2157 - val_accuracy: 0.8665 - val_loss: 0.4073
Epoch 4/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 188s 143ms/step - accuracy: 0.9379 - loss: 0.1764 - val_accuracy: 0.8656 - val_loss: 0.4345
Epoch 5/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 188s 143ms/step - accuracy: 0.9466 - loss: 0.1496 - val_accuracy: 0.8616 - val_loss: 0.4618
Epoch 5: early stopping
Restoring model weights from the end of the best epoch: 2.


In [67]:
y_pred1=model1.predict(x_test)

1125/1125 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step


In [68]:
y_pred1

array([[9.98836197e-03, 3.42515318e-06, 8.40544328e-03, 9.81602848e-01],
       [9.99561608e-01, 5.95800811e-05, 1.26769693e-04, 2.52074853e-04],
       [4.63186987e-02, 1.56971887e-02, 9.21585739e-01, 1.63983144e-02],
       ...,
       [5.80254337e-03, 1.77803263e-03, 1.45834545e-02, 9.77836013e-01],
       [6.66348310e-03, 5.25852316e-04, 9.91389573e-01, 1.42107322e-03],
       [9.97809708e-01, 3.88580629e-05, 7.28203508e-04, 1.42322376e-03]],
      shape=(36000, 4), dtype=float32)

In [69]:
y_pred1_labels=np.argmax(y_pred1,axis=1)

In [70]:
y_pred1_labels

array([3, 0, 2, ..., 3, 2, 0], shape=(36000,))

In [71]:
print(confusion_matrix(y_test,y_pred1_labels))

[[7763  356  463  418]
 [ 328 8254  259  159]
 [ 327  229 7661  783]
 [ 272  258  749 7721]]


In [72]:
print(accuracy_score(y_test,y_pred1_labels))

0.8721944444444445


In [73]:
print(classification_report(y_test,y_pred1_labels))

              precision    recall  f1-score   support

           0       0.89      0.86      0.88      9000
           1       0.91      0.92      0.91      9000
           2       0.84      0.85      0.85      9000
           3       0.85      0.86      0.85      9000

    accuracy                           0.87     36000
   macro avg       0.87      0.87      0.87     36000
weighted avg       0.87      0.87      0.87     36000



In [74]:
print(log_loss(y_test,y_pred1))

0.3675707170440858


In [75]:
print(roc_auc_score(y_test,y_pred1,multi_class='ovr'))

0.9744771203703704


Now Implementing GlobalAveragePool1d

In [86]:
from tensorflow.keras.layers import GlobalAveragePooling1D

In [103]:
model2=Sequential([
    Input(shape=(sentence_length,))
])

In [104]:
model2.add(Embedding(input_dim=vocab_size,output_dim=vector_representation_size))

In [105]:
model2.add(Dropout(0.3))

In [106]:
model2.add(GlobalAveragePooling1D())

In [107]:
model2.add(Dropout(0.3))

In [108]:
model2.add(Dense(4,activation='softmax'))

In [109]:
model2.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [110]:
model2.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 38s 29ms/step - accuracy: 0.7027 - loss: 0.9228 - val_accuracy: 0.8319 - val_loss: 0.5482
Epoch 2/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 40s 31ms/step - accuracy: 0.8581 - loss: 0.4545 - val_accuracy: 0.8633 - val_loss: 0.4223
Epoch 3/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 41s 31ms/step - accuracy: 0.8840 - loss: 0.3591 - val_accuracy: 0.8703 - val_loss: 0.3896
Epoch 4/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 41s 32ms/step - accuracy: 0.8993 - loss: 0.3104 - val_accuracy: 0.8709 - val_loss: 0.3819
Epoch 5/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 41s 31ms/step - accuracy: 0.9086 - loss: 0.2790 - val_accuracy: 0.8764 - val_loss: 0.3718
Epoch 6/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 41s 31ms/step - accuracy: 0.9161 - loss: 0.2549 - val_accuracy: 0.8734 - val_loss: 0.3731
Epoch 7/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 41s 31ms/step - accuracy: 0.9225 - loss: 0.2357 - val_accuracy: 0.8749 - val_loss: 0.3741
Epoch 8/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 40s 30ms/step - accuracy: 0.9262 -

In [112]:
y_pred2=model2.predict(x_test)

1125/1125 ━━━━━━━━━━━━━━━━━━━━ 1s 673us/step


In [114]:
y_pred2_values=np.argmax(y_pred,axis=1)

In [115]:
print(classification_report(y_test,y_pred2_values))

              precision    recall  f1-score   support

           0       0.89      0.86      0.87      9000
           1       0.91      0.91      0.91      9000
           2       0.84      0.85      0.84      9000
           3       0.84      0.86      0.85      9000

    accuracy                           0.87     36000
   macro avg       0.87      0.87      0.87     36000
weighted avg       0.87      0.87      0.87     36000



In [116]:
print(accuracy_score(y_test,y_pred2_values))

0.8669444444444444


In [118]:
print(confusion_matrix(y_test,y_pred2_values))

[[7724  386  502  388]
 [ 319 8169  268  244]
 [ 328  207 7611  854]
 [ 350  214  730 7706]]


In [119]:
print(log_loss(y_test,y_pred2))

0.40020377431405096


In [121]:
print(roc_auc_score(y_test,y_pred,multi_class='ovr'))

0.9702741260288066
