In [139]:
import pandas as pd
import numpy as np

In [140]:
df=pd.read_csv('ecommerceDataset.csv',header=None,names=['Household','desc'])

In [141]:
df

Household                                               desc
0        Household  Paper Plane Design Framed Wall Hanging Motivat...
1        Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2        Household  SAF 'UV Textured Modern Art Print Framed' Pain...
3        Household  SAF Flower Print Framed Painting (Synthetic, 1...
4        Household  Incredible Gifts India Wooden Happy Birthday U...
...            ...                                                ...
50420  Electronics  Strontium MicroSD Class 10 8GB Memory Card (Bl...
50421  Electronics  CrossBeats Wave Waterproof Bluetooth Wireless ...
50422  Electronics  Karbonn Titanium Wind W4 (White) Karbonn Titan...
50423  Electronics  Samsung Guru FM Plus (SM-B110E/D, Black) Colou...
50424  Electronics                   Micromax Canvas Win W121 (White)

[50425 rows x 2 columns]

In [142]:
df['Household'].isnull().sum()

np.int64(0)

In [143]:
df

Household                                               desc
0        Household  Paper Plane Design Framed Wall Hanging Motivat...
1        Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2        Household  SAF 'UV Textured Modern Art Print Framed' Pain...
3        Household  SAF Flower Print Framed Painting (Synthetic, 1...
4        Household  Incredible Gifts India Wooden Happy Birthday U...
...            ...                                                ...
50420  Electronics  Strontium MicroSD Class 10 8GB Memory Card (Bl...
50421  Electronics  CrossBeats Wave Waterproof Bluetooth Wireless ...
50422  Electronics  Karbonn Titanium Wind W4 (White) Karbonn Titan...
50423  Electronics  Samsung Guru FM Plus (SM-B110E/D, Black) Colou...
50424  Electronics                   Micromax Canvas Win W121 (White)

[50425 rows x 2 columns]

In [144]:
df['desc'].isnull().sum()

np.int64(1)

In [145]:
df=df.dropna(axis=0) #dropped the empty entry via row

In [146]:
df

Household                                               desc
0        Household  Paper Plane Design Framed Wall Hanging Motivat...
1        Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2        Household  SAF 'UV Textured Modern Art Print Framed' Pain...
3        Household  SAF Flower Print Framed Painting (Synthetic, 1...
4        Household  Incredible Gifts India Wooden Happy Birthday U...
...            ...                                                ...
50420  Electronics  Strontium MicroSD Class 10 8GB Memory Card (Bl...
50421  Electronics  CrossBeats Wave Waterproof Bluetooth Wireless ...
50422  Electronics  Karbonn Titanium Wind W4 (White) Karbonn Titan...
50423  Electronics  Samsung Guru FM Plus (SM-B110E/D, Black) Colou...
50424  Electronics                   Micromax Canvas Win W121 (White)

[50424 rows x 2 columns]

In [147]:
print(df['Household'].value_counts())

Household
Household                 19313
Books                     11820
Electronics               10621
Clothing & Accessories     8670
Name: count, dtype: int64


In [148]:
print(df['Household'].value_counts(normalize=True))

Household
Household                 0.383012
Books                     0.234412
Electronics               0.210634
Clothing & Accessories    0.171942
Name: proportion, dtype: float64


In [149]:
df.isnull().sum()

Household    0
desc         0
dtype: int64

In [150]:
df=df.reset_index(drop=True)

In [151]:
import re

In [152]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [153]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\swapn\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\swapn\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [154]:
lemmatizer=WordNetLemmatizer()

In [155]:
corpus=[]
stop_words=stopwords.words('english')
for i in range(0,len(df)):
    review=re.sub('[^a-zA-Z]',' ',df['desc'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if not word in stop_words]
    review=' '.join(review)
    corpus.append(review)

In [156]:
corpus

['paper plane design framed wall hanging motivational office decor art print x inch set painting made synthetic frame uv textured print give multi effect attracts towards special series painting make wall beautiful give royal touch painting ready hang would proud possess unique painting niche apart use modern efficient printing technology print ink precision epson roland hp printer innovative hd printing technique result durable spectacular looking print highest last lifetime print solely top notch ink achieve brilliant true colour due high level uv resistance print retain beautiful colour many year add colour style living space digitally printed painting pleasure eternal bliss bring home elegant print lushed rich color make nothing sheer elegance friend family would treasured forever whoever lucky recipient liven place intriguing painting high definition hd graphic digital print home office room',
 'saf floral framed painting wood inch x inch special effect uv print textured sao paint

In [157]:
lengths=[len(i.split())for i in corpus]
sentence_length=int(np.percentile(lengths,99))

In [158]:
print(sentence_length)

376


In [159]:
y=df['Household']

In [160]:
from sklearn.preprocessing import LabelEncoder

In [161]:
label_encoder=LabelEncoder()

In [162]:
y=label_encoder.fit_transform(y)

In [163]:
y

array([3, 3, 3, ..., 2, 2, 2], shape=(50424,))

In [164]:
y=np.array(y)

In [165]:
y

array([3, 3, 3, ..., 2, 2, 2], shape=(50424,))

In [166]:
each_vector_length=100

In [167]:
from tensorflow.keras.layers import Dense,LSTM,Bidirectional,Dropout,Input,Embedding
from tensorflow.keras.models import Sequential

In [168]:
from sklearn.model_selection import train_test_split

In [169]:
x_train_text,x_test_text,y_train,y_test=train_test_split(corpus,y,test_size=0.3,stratify=y,random_state=42)

In [170]:
from tensorflow.keras.layers import TextVectorization

In [171]:
tv=TextVectorization(output_mode='int',output_sequence_length=sentence_length,max_tokens=20000)

In [172]:
tv.adapt(x_train_text)
x_train=tv(x_train_text)
x_test=tv(x_test_text)

In [173]:
x_train.shape,y_train.shape

(TensorShape([35296, 376]), (35296,))

In [174]:
import tensorflow 

In [175]:
early_stopping=tensorflow.keras.callbacks.EarlyStopping(
    min_delta=0.001,
    patience=3,
    monitor='val_loss',
    restore_best_weights=True,
    verbose=1
)

In [176]:
vocabulary_size=len(tv.get_vocabulary())

In [177]:
vocabulary_size

20000

In [178]:
model_lstm=Sequential([
    Input(shape=(sentence_length,))
])

In [179]:
model_lstm.add(Embedding(input_dim=vocabulary_size,output_dim=each_vector_length,mask_zero=True)) #mask_zero ignores the padding added

In [180]:
model_lstm.add(Dropout(0.3))

In [181]:
model_lstm.add(LSTM(64))

In [182]:
model_lstm.add(Dropout(0.3))

In [183]:
model_lstm.add(Dense(len(np.unique(y)),activation='softmax'))

In [184]:
from tensorflow.keras.optimizers import AdamW

In [185]:
model_lstm.compile(loss='sparse_categorical_crossentropy',optimizer=AdamW(learning_rate=1e-3,clipnorm=1.0),metrics=['accuracy'])
#the global gradient vectoor will be normalized to no more than 1

In [186]:
model_lstm.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 376, 100)       │     2,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 376, 100)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 64)             │        42,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 4)              │           260 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,042,500 (7.79 MB)

 Trainable params: 2,042,500 (7.79 MB)

 Non-trainable params: 0 (0.00 B)

In [187]:
# model_lstm.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64,callbacks=[early_stopping])

In [188]:
y_pred=model_lstm.predict(x_test)

  6/473 ━━━━━━━━━━━━━━━━━━━━ 24s 53ms/step

473/473 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step


In [189]:
y_pred_labels=np.argmax(y_pred,axis=1)

In [190]:
y_pred_labels

array([2, 1, 2, ..., 3, 1, 2], shape=(15128,))

In [191]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,log_loss,roc_auc_score

In [192]:
print(classification_report(y_test,y_pred_labels))

              precision    recall  f1-score   support

           0       0.21      0.23      0.22      3546
           1       0.19      0.29      0.23      2601
           2       0.18      0.28      0.22      3187
           3       0.40      0.17      0.24      5794

    accuracy                           0.23     15128
   macro avg       0.24      0.24      0.23     15128
weighted avg       0.27      0.23      0.23     15128



In [193]:
print(accuracy_score(y_test,y_pred_labels))

0.22580645161290322


In [194]:
print(confusion_matrix(y_test,y_pred_labels))

[[ 799  841 1308  598]
 [ 699  746  814  342]
 [ 956  784  885  562]
 [1398 1548 1862  986]]


In [195]:
print(log_loss(y_test,y_pred))

1.3870482998368137


In [196]:
print(roc_auc_score(y_test,y_pred,multi_class='ovr'))

0.4879214863956085


In [197]:
def printallmetrics(name,y_true,y_pred,y_prob=None):
    print(f"{name}\n")
    print(f"accuracy:\n{accuracy_score(y_true,y_pred)}")
    print(f"classification report:\n{classification_report(y_true,y_pred)}")
    print(f"confusion matrix:\n{confusion_matrix(y_true,y_pred)}")
    
    if y_prob is not None:
        print(f"log loss:\n{log_loss(y_true,y_prob)}")
        print(f"roc auc score:\n{roc_auc_score(y_true,y_prob,multi_class='ovr')}")

trying TF-IDF + logistic regression

In [198]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [199]:
tfidf=TfidfVectorizer(max_features=20000,ngram_range=(1,3))

In [200]:
x_train_tfidf=tfidf.fit_transform(x_train_text)

In [201]:
x_test_tfidf=tfidf.transform(x_test_text)

In [202]:
from sklearn.linear_model import LogisticRegression

In [203]:
model_logr=LogisticRegression(max_iter=10000,multi_class='ovr')

In [204]:
model_logr.fit(x_train_tfidf,y_train)

c:\Users\swapn\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=10000, multi_class='ovr')

In [205]:
y_pred_logr=model_logr.predict(x_test_tfidf)

In [206]:
y_pred_logr

array([3, 0, 1, ..., 3, 2, 3], shape=(15128,))

In [207]:
y_pred_logr_probabilisitic=model_logr.predict_proba(x_test_tfidf)

In [208]:
printallmetrics("logistic regression",y_test,y_pred_logr,y_pred_logr_probabilisitic)

logistic regression

accuracy:
0.9637757800105764
classification report:
              precision    recall  f1-score   support

           0       0.97      0.95      0.96      3546
           1       0.97      0.98      0.97      2601
           2       0.97      0.94      0.96      3187
           3       0.95      0.98      0.96      5794

    accuracy                           0.96     15128
   macro avg       0.97      0.96      0.96     15128
weighted avg       0.96      0.96      0.96     15128

confusion matrix:
[[3371   27   26  122]
 [   8 2537   11   45]
 [  46    7 3006  128]
 [  40   35   53 5666]]
log loss:
0.19345855796069283
roc auc score:
0.992802297924701


Now implementing SVM (linear)

In [209]:
from sklearn.svm import LinearSVC

In [210]:
svm_model=LinearSVC(multi_class='ovr')

In [211]:
svm_model.fit(x_train_tfidf,y_train)

LinearSVC()

In [212]:
y_pred_svm=svm_model.predict(x_test_tfidf)

In [213]:
y_pred_svm

array([3, 0, 1, ..., 3, 2, 3], shape=(15128,))

In [214]:
printallmetrics("svm",y_test,y_pred_svm)

svm

accuracy:
0.9762030671602326
classification report:
              precision    recall  f1-score   support

           0       0.98      0.96      0.97      3546
           1       0.98      0.98      0.98      2601
           2       0.98      0.97      0.97      3187
           3       0.97      0.99      0.98      5794

    accuracy                           0.98     15128
   macro avg       0.98      0.98      0.98     15128
weighted avg       0.98      0.98      0.98     15128

confusion matrix:
[[3419   21   26   80]
 [   5 2560   10   26]
 [  27    5 3079   76]
 [  26   19   39 5710]]


Implementing NaiveBayes

In [215]:
from sklearn.naive_bayes import MultinomialNB

In [216]:
nb_model=MultinomialNB()

In [217]:
nb_model.fit(x_train_tfidf,y_train)

MultinomialNB()

In [218]:
y_pred_nb=nb_model.predict(x_test_tfidf)

In [241]:
df['Household'].unique()

array(['Household', 'Books', 'Clothing & Accessories', 'Electronics'],
      dtype=object)

In [219]:
printallmetrics("naive bayes",y_test,y_pred_nb)

naive bayes

accuracy:
0.9474484399788472
classification report:
              precision    recall  f1-score   support

           0       0.97      0.92      0.95      3546
           1       0.96      0.97      0.96      2601
           2       0.95      0.92      0.94      3187
           3       0.93      0.97      0.95      5794

    accuracy                           0.95     15128
   macro avg       0.95      0.94      0.95     15128
weighted avg       0.95      0.95      0.95     15128

confusion matrix:
[[3267   41   48  190]
 [   5 2510   17   69]
 [  45    7 2947  188]
 [  39   57   89 5609]]


In [220]:
type(review)

str

In [251]:
def predict_text(text):
    review=re.sub('[^a-zA-Z]',' ',text)
    review=review.lower().split()
    review=[lemmatizer.lemmatize(word) for word in review if word not in stop_words]
    review=' '.join(review)
    
    vector=tfidf.transform([review])
    
    pred_num=model_logr.predict(vector)
    pred_label=label_encoder.inverse_transform(pred_num)
    
    return pred_label[0],int(pred_num[0])

In [260]:
sample=str(input("enter any sentence"))
sample_name,sample_num=predict_text(sample)
print(sample_name," ",sample_num)

Books   0
