In [450]:
import tensorflow as tf
import numpy as np

In [451]:
from tensorflow.keras.preprocessing.text import one_hot #this is for one hot encoding using tf

In [452]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [453]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [454]:
vocabulary_size=10000 #this is like defining the length of your OHE matrix, it's basically the dimension, you can take any value as this is a hyperparameter

In [455]:
onehot_repr=[one_hot((words),(vocabulary_size))for words in sent] #this captures the indices of where the word is present in in the matrix

In [456]:
print(onehot_repr)

[[1308, 6846, 6121, 5831], [1308, 6846, 6121, 4479], [1308, 4216, 6121, 6458], [586, 113, 6658, 1977, 3310], [586, 113, 6658, 1977, 1302], [8810, 1308, 2528, 6121, 4010], [2394, 8566, 5301, 1977]]


In [457]:
from tensorflow.keras.utils import pad_sequences #we add padding as while training our NN, each of the sentence should be of the same size, in our case some are 4 and some are 5, so by applying padding (esentially just adding zeroes before or after the indice values we can make every sentence's length the same)

In [458]:
sent_length=7 #i set it to 7 so that all the sentences lengrh will be 7, just keepin it constant

In [459]:
embedded_docs=pad_sequences(onehot_repr,maxlen=sent_length,dtype='int32',padding='pre') #(your ohe matrix,sent_length to pad to, padding do you want it before or after)

In [460]:
embedded_docs=np.expand_dims(embedded_docs,axis=0) #adding the batch dimension

In [461]:
print(embedded_docs)

[[[   0    0    0 1308 6846 6121 5831]
  [   0    0    0 1308 6846 6121 4479]
  [   0    0    0 1308 4216 6121 6458]
  [   0    0  586  113 6658 1977 3310]
  [   0    0  586  113 6658 1977 1302]
  [   0    0 8810 1308 2528 6121 4010]
  [   0    0    0 2394 8566 5301 1977]]]


In [462]:
dimension=10 #this is basically how many vectors we show

In [463]:
from tensorflow.keras.models import Sequential

In [464]:
from tensorflow.keras.layers import Embedding,Input

In [465]:
model = Sequential([
    Input(shape=(sent_length,)),   
    Embedding(input_dim=vocabulary_size,
              output_dim=dimension)
])

In [466]:
model.compile('adam','mse')

In [467]:
print(embedded_docs.shape)

(1, 7, 7)


In [468]:
model.summary()

Model: "sequential_25"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_32 (Embedding)        │ (None, 7, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [469]:
embedded_docs[0]

array([[   0,    0,    0, 1308, 6846, 6121, 5831],
       [   0,    0,    0, 1308, 6846, 6121, 4479],
       [   0,    0,    0, 1308, 4216, 6121, 6458],
       [   0,    0,  586,  113, 6658, 1977, 3310],
       [   0,    0,  586,  113, 6658, 1977, 1302],
       [   0,    0, 8810, 1308, 2528, 6121, 4010],
       [   0,    0,    0, 2394, 8566, 5301, 1977]], dtype=int32)

In [473]:
model.predict(embedded_docs[0])